### ISSUE TITLE
Fail to install the package in Window and Linux

### ISSUE THREAD

**Issue by Spatial-R** [jameshay218/driftSim#2]
This package is impressive which has linked the receptor binding avidity to the evolutionary dynamic of influenza. However, i have tested the installation in Windows and Linux.  Neither of those two ways can install the package.

**Comment by jameshay218** [comment]
Thanks for raising this. I was getting the following error, which has now been fixed:

```
*** installing help indices
  converting help for package 'driftSim'
    finding HTML links ... done
    calculate_deltaV_matrix                 html  
Error: C:/Users/James/AppData/Local/Temp/Rtmp0OZLtE/devtools16f873b2497d/jameshay218-driftSim-0e660ae/man/calculate_deltaV_matrix.Rd:10: Bad \link text
* removing 'C:/Users/James/Documents/R/win-library/3.4/driftSim'
In R CMD INSTALL
```
